# Data Encoding

(1) Nominal/OHE Encoding

(2) Label and Ordinal Encoding

(3) Target Guided Ordinal Encoding

In [ ]:
# Converting categorical values into numerical values because model only understand numerical values.

(1) Nominal or One Hot Encoding

This technique is used to represent categorical data as numerical data.

disdvantages  - we have 100 categories it will create 100 new features
             
              - Sparse matrix (1s,0s) -> cause overfitting

In [7]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [8]:
## Create a simple dataframe
df= pd.DataFrame({
        'color' : ['red','blue','green','green','red','blue']
    })

In [9]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [11]:
## Create an instance of OneHotencoder
encoder= OneHotEncoder()

In [15]:
#Perform fit and tranform 
encoded=encoder.fit_transform(df[['color']]).toarray()

In [17]:
import pandas as pd
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [20]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [21]:
encoder.transform([['blue']]).toarray()

c:\Users\Manis\OneDrive\vs COdE Python\Data-Science-Journey\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [22]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [23]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]